In [ ]:
#This code is based and inspired by the example of python course last week. It realises the game.
import numpy as np
import scipy.linalg as LA
import sympy as sp
#Inspired by the stick game last week
n=int(input('please input the size of the grid'))
matrix=np.zeros((n,n))#I first use a 0-matrix as initial matrix, but that leads to a misunderstanding
matrix[matrix == 0] = 2# Use 2 as a placeholder
print(matrix)
#Here I prooduce a all_0_matrix, 0 here as a placeholder, to reduce misunderstanding, following step will ask user to re-fill 0 where they want to place.

def verify(a, k):# This is for verify if the coordinate has been used or not
    while a in k:
        print(a, 'is used')
        i=int(input('Please input the ROW in the grid you want to place 0(1 to n)'))-1
        j=int(input('Please input the Column in the grid you want to place 0(1 to n)'))-1
        a=(i,j)
    return a

def game(player):
    Used_Coordinate=set()# create an empty set to place the coordinate that used 
    i=0
    i=i+1
    while len(Used_Coordinate)<n*n:
        #I tried to follow the thought of programming brfore, but under while true, not able to use, hence I use another way to prevent overflow 
        print('This is the turn of',player) 
        if player=='Human':
            take_Row=int(input('Please input the ROW in the grid you want to place 0(0 to n-1)'))
            take_Column=int(input('Please input the Column in the grid you want to place 0(0 to n-1)'))
            coordinate=(take_Row, take_Column)# Uniformly using base_0 coordinate
            valid_coordinate = verify(coordinate, Used_Coordinate)
            Used_Coordinate.add(valid_coordinate)
            # place the coordinate used into my set
        #user then can straightly input from 1 to n instead starts from 0
            matrix[take_Row][take_Column]=0
        
        if player=='Bot':
            while True:
                take_Row = np.random.randint(0,n)
                take_Column= np.random.randint(0,n)
                Bot_coordinate=(take_Row,take_Column)
                if Bot_coordinate not in Used_Coordinate:
                    matrix[take_Row][take_Column] = 1
                    Used_Coordinate.add(Bot_coordinate)
                    break
        print(matrix)
        player = "Bot" if player == "Human" else "Human"
    if LA.det(matrix)==0:
        print('You Win!')
    else:
        print('You Lose!')
        
x=input('Who starts first, Human, or Bot?')
game(x)

please input the size of the grid3
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]
Who starts first, Human, or Bot?Human
This is the turn of Human
Please input the ROW in the grid you want to place 0(0 to n-1)2
Please input the Column in the grid you want to place 0(0 to n-1)2
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 0.]]
This is the turn of Bot
[[2. 2. 1.]
 [2. 2. 2.]
 [2. 2. 0.]]
This is the turn of Human
Please input the ROW in the grid you want to place 0(0 to n-1)1
Please input the Column in the grid you want to place 0(0 to n-1)1
[[2. 2. 1.]
 [2. 0. 2.]
 [2. 2. 0.]]
This is the turn of Bot
[[2. 2. 1.]
 [2. 0. 1.]
 [2. 2. 0.]]
This is the turn of Human
